{% set version = "0.2.2" %}
{% set sha256 = "4e72fbe4d44cf16656e2287421b1e97233400f89bcbb34a046bc18d1e614aac3" %}
{% set openjdk_version = "8.0.121" %}

package:
  name: scijava-jupyter-kernel
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/hadim/scijava-jupyter-kernel/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win or linux32]

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - notebook
    - jupyterlab

test:
  requires:
    - jupyter_client
  commands:
    - conda list scijava-jupyter-kernel

about:
  home: https://github.com/hadim/scijava-jupyter-kernel
  license: Apache
  license_file: LICENSE
  summary: 'A Java kernel for Jupyter.'
  description: A Java kernel for Jupyter.
  doc_url: https://imagej.net/Scijava_Jupyter_Kernel
  dev_url: https://github.com/hadim/scijava-jupyter-kernel

extra:
  recipe-maintainers:
    - hadim
