{% set version = "0.2.1" %}
{% set sha256 = "7065f5d2fa74b7b33e3a7410913a59a0d74cb6f560cae254fef62156a48209a3" %}

package:
  name: scijava-jupyter-kernel
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/hadim/scijava-jupyter-kernel/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or linux32]

requirements:
  build:
    - openjdk
    - maven  # [not win]
  run:
    - openjdk
    - notebook
    - jupyterlab

test:
  requires:
    - jupyter_client
  commands:
    - conda list scijava-jupyter-kernel

about:
  home: https://github.com/hadim/scijava-jupyter-kernel
  license: Apache
  license_file: LICENSE
  summary: 'A Java kernel for Jupyter.'
  description: A Java kernel for Jupyter.
  doc_url: https://imagej.net/Scijava_Jupyter_Kernel
  dev_url: https://github.com/hadim/scijava-jupyter-kernel

extra:
  recipe-maintainers:
    - hadim
