travis:
  secure:
    BINSTAR_TOKEN: HvHVrICRYId4ZSuGRpXZ1rAcQSfS6wDN3SodrTOfCMzEgHFkSoLL4wk8oIIO/8HRQItz8cghoD0WLCEjhHFKaXrGHC3o53ECIbL2O4fjBjhNXS3F6ma/G8zqN59iH0u0F+jaWTtQTui2fKvrrPYIhvcQdXwKlxWCFsx3QGEOFQh+bovKD7wxDvx/hl/iW7AjZfm8v1A2nfkI0d06/aFKNfYral6eYH+zMoAbBIXkHVEXieDRJsNxFcVCQSyrygLi9w+VPp+pcIkSgcSEGQz9MG2pawtOWfv9peS67JYRA5paw+Xk+eHQCK430QCHrdpkWWDjwotdoGE3g/T6jp3SfBck/jeXAVSeoluf42AeXY4nYK0x7fJJCLsqnGB53Zu7pBzylazfuoqLU49L0r7x6HhFwS4rNfqFz8b4LJvSVokfZczyOIyeoDJ/J0MKtrVsDmQWb2M9XZ9Xh8ifqvryDwlF3Bx6GvajAg5vha1UF7xMYxZpH0VmMBGI68lPw/f4LpI7ftDwk8fDOE6hmljv/WmSDApo8+8kmzg3SBWFQmJ5ucYjx3+0VJAx5aANYkuaybo+cy5WGqdvDSzYtVsAk/OXXxZYhwONXITrXCEkiSNNHr15yLenuVI8vN/QWaCFN4bMRcWiM0eXHhd1F58ghWN6I1TPDg2kgwmwGhbgUJs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
